config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  root "pages#home"
  get "pages/home", to: "pages#home"
  get "/signup", to: "chefs#new"
  resources :recipes
  resources :chefs , except: [:new]

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chef.rb
class Chef < ApplicationRecord
before_save {self.email = email.downcase}

VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
validates :chefname, presence: true,length: {maximum: 30}
validates :email, presence: true, length: { maximum: 255},
          format: {with: VALID_EMAIL_REGEX},uniqueness: {case_sensitive: false}

has_many :recipes, dependent: :destroy
has_secure_password
validates :password,presence: true, length: {minimum:6} , allow_nil: true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  validates :name , presence: true
  validates :description, presence: true, length: {minimum: 10, maximum: 500}

  belongs_to :chef
  validates :chef_id, presence: true
  # to get recent recipes
  default_scope -> {order(updated_at: :desc)}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?

  def current_user
    if session[:chef_id]
      begin
        @current_chef = Chef.find(session[:chef_id])
      rescue ActiveRecord::RecordNotFound => e
        redirect_to root_path
      end
    end
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:danger] = 'You must be logged in!'
      redirect_to root_path
    end
  end
end

app/controllers/chefs_controller.rb
class ChefsController < ApplicationController
  before_action :get_chef, only: [:show,:edit,:update,:destroy]
  before_action :require_same_user, only: [:edit,:update,:destroy]
  before_action :require_admin , only: [:destroy]

  def index
    @chefs = Chef.paginate(page: params[:page], per_page: 5)
  end
  def new
    @chef = Chef.new
  end

  def create
    @chef = Chef.new(chef_params)
    if @chef.save
      session[:chef_id] = @chef.id
      flash[:success] = 'Account created!'
      redirect_to chef_path(@chef)
    else
      render 'new'
    # break
    end
  end

  def show
    @chef_recipes = @chef.recipes.paginate(page: params[:page], per_page: 5)
  end

  def edit
  end

  def update
    if @chef.update(chef_params)
      flash[:success] = 'Profile successfully updated!'
      redirect_to @chef
    else
      render 'edit'
    end
  end

  def destroy
    if !@chef.admin?
      if @chef.destroy
        flash[:success] = "User #{@chef.chefname} and all thoughts are deleted"
        session[:chef_id] = nil
        redirect_to chefs_path
      end
    end
  end

  private
    def chef_params
      params.require(:chef).permit( :chefname, :email, :password, :password_confirmation )
    end

    def get_chef
      @chef = Chef.find(params[:id])
    end

    def require_same_user
      if logged_in? && current_user != @chef && !current_user.admin?
        flash[:danger] = 'You can edit your profile only!'
        redirect_to @chef
      end
    end

    def require_admin
      if logged_in? && !current_user.admin?
        flash[:danger] = 'Restricted action! Check with Admin Team'
        redirect_to chefs_path
      end
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    if logged_in?
      redirect_to recipes_path
    end
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:edit, :show, :update, :destroy]
  before_action :require_user, except: [:index,:show]
  before_action :require_same_user , only: [:edit, :update, :destroy]

  def index
    @recipes = Recipe.paginate(page: params[:page], per_page: 5)
  end
  def show
    @recipe = Recipe.find(params[:id])
  end
  #  protected
  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_param)
    @recipe.chef = current_user
    if @recipe.save
      flash[:success] = 'Thought uploaded successfully'
      redirect_to recipe_path(@recipe)
    else
      render 'recipes/new'
    end
  end

  def edit
  end

  def update
    @recipe = Recipe.find(params[:id])
    if @recipe.update(recipe_param)
      flash[:success] = 'Thought updated successfully'
      redirect_to recipe_path(@recipe)
    else
      render 'edit'
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    if @recipe.destroy
      flash[:success] = 'Thought Deleted'
      redirect_to recipes_path
    end
  end

  private
    def recipe_param
      #white list the parameters
      params.require(:recipe).permit(:name, :description)
    end

    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    def require_same_user
      if current_user != @recipe.chef && !current_user.admin?
        flash[:danger] = 'You can edit your Thoughts only!'
        redirect_to recipes_path
      end
    end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    chef = Chef.find_by(email: params[:session][:email].downcase)
      if chef && chef.authenticate(params[:session][:password])
        session[:chef_id] = chef.id
        flash[:success] = 'You have Logged In successfully'
        redirect_to chef_path(chef)
      else
        flash.now[:danger] = "Invalid Email/Password"
        render 'new'
      end
  end

  def destroy
      session[:chef_id] = nil
      flash[:success] = 'Logged out successfully'
      redirect_to root_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar"
    image_tag(gravatar_url, alt: user.chefname, 
                              class: "img-circle")
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/chefs/_form.html.erb
<%= render "shared/errors", orm: @chef %>
<div class="row">
  <div class="col-md-12">
  <%= form_with model: @chef, :html => { class:"form-horizontal" , role:"form"} do |form| %>
      <div class="form-group">
          <div class="control-label col-md-2">
            <%= form.label :chefname , "User Name"%>
          </div>
          <div class="col-md-8">
            <%= form.text_field :chefname, class:"form-control",placeholder:'User Name', autofocus: true %>
          </div>
        </div>
        <div class="form-group">
          <div class="control-label col-md-2">
            <%= form.label :email %><br/>
          </div>
          <div class="col-md-8">
            <%= form.email_field :email, class:"form-control",placeholder:'Email ID' %>
          </div>
          </div>
          <div class="form-group">
          <div class="control-label col-md-2">
            <%= form.label :password %><br/>
          </div>
          <div class="col-md-8">
            <%= form.password_field :password, class:"form-control",placeholder:'Enter Password' %>
          </div>
          </div>
            <div class="form-group">
          <div class="control-label col-md-2">
            <%= form.label :password_confirmation %><br/>
          </div>
          <div class="col-md-8">
            <%= form.password_field :password_confirmation, class:"form-control",placeholder:'Password Confirmation' %>
          </div>
          </div>
        <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
          <%= form.submit action_text, class:"btn btn-primary btn-lg btn-small"%>
          </div>
        </div>
  <% end %>
<div class="col-md-offset-4">
  <%= link_to "Back to Home Page", root_path,class:"btn btn-danger btn-small" %>
</div>
 </div>

app/views/chefs/edit.html.erb
<%= render 'shared/pagetitle', pageTitle: 'Edit profile'%>
<%= render 'form', action_text: 'Update account'%>

app/views/chefs/index.html.erb
<%= render 'shared/pagetitle', pageTitle: 'Listing all Users'%>
<div align="center">
<%= will_paginate %>
</div>
<div align="center">
  <% @chefs.each do |chef|%>
      <div class="row">
        <ul class="listing">
        <div class="well col-md-4 col-md-offset-4 center">
          <li><%= link_to gravatar_for(chef,size:150), chef_path(chef) %></li>
          <li class="chef-title"><%= link_to chef.chefname.capitalize, chef_path(chef)%></li>
          <%= pluralize(chef.recipes.count , 'Thought') if chef.recipes.count >= 0 %>
          <% if logged_in? && current_user.admin? && !chef.admin? %>
          <li> <%= button_to 'Delete User', chef_path(chef), method: :delete ,class: "btn btn-danger" %></li>
          <%end%>
          <br/>
        </div>
        </ul>
    </div>
  <% end %>
</div>
<div align="center">
<%= will_paginate %>
</div>

app/views/chefs/new.html.erb
<%= render 'shared/pagetitle', pageTitle: 'Sign Up'%>
<%= render 'form', action_text: 'Create Account'%>

app/views/chefs/show.html.erb
<%= render 'shared/pagetitle', pageTitle: "Profile of: #{@chef.chefname.capitalize}" %>
  <div class="row">
    <div class="col-md-4 col-md-offset-4 center">
    <%# <%= gravatar_for(@chef,size:150) %>
    </div>
</div>
</div>
<div class="container">
 <div align="center">
 <%= will_paginate @chef_recipes%>
 </div>
   <%= render 'recipes/listings', obj: @chef_recipes %>
 </div>
 <div align="center">
 <%= will_paginate @chef_recipes%>
 </div>

app/views/layouts/_flash_message.html.erb
<% if !flash.empty? %>
  <div class="col col-md10 col-offset-1">
    <% flash.each do |name,msg|%>
      <div class="alert alert-<%=name%> alert-dismissible" >
        <a href="" class="close" data-dismiss="alert"> &#215; </a>
        <%= msg %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Train of Thoughts</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", media: 'all', "data-turbolink-track": "reload" %>
    <%= javascript_tag "application", "data-turbolink-track": "reload" %>
  </head>
  <body>
  <%= render "pages/navbar" %>
  <%= render "layouts/flash_message" %>
  <div class="container">
    <%= yield %>
    </div>
  </body>
  <%= render "pages/footer" %>
</html>

app/views/pages/_footer.html.erb
<footer class="text-muted py-5">
  <div class="container">
    <p class="float-end mb-1">
      <%# <a href="#">Back to top</a> %>
      <%= link_to "Back to All Blogs", recipes_path%>
    </p>
    <%# <p class="mb-1">Home and See more ?</p> %>
    <%= link_to "Home and See more ?", root_path%>
    <p class="mb-0">New to Rails ?<a href="/">
  </div>
</footer>

app/views/pages/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
       <%= link_to "R-R Blogs", root_path, class:"navbar-brand", id:"logo"%>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to "All Users", chefs_path%></span></li>
        <li><%= link_to "All Blogs", recipes_path %></li>
       <% if logged_in? %>
        <li><%= link_to "Create New", new_recipe_path %></li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
       <% unless logged_in? %>
          <li><%= link_to "Sign In", login_path %></li>
        <% else %>
        <% if current_user.admin? %>
<li><%= link_to "Super User Account" , chef_path(current_user)%></li>
<%else%>
           <li><%= link_to "#{current_user.chefname.capitalize}'s Account" , chef_path(current_user)%></li>
           <%end%>
           <li role='separator' class="divider"></li>
           <li><%= link_to "Edit Account", edit_chef_path(current_user)%></li>
           <li role='separator' class="divider"></li>
           <li><%= button_to "Sign Out", logout_path, method: :delete, class:'lo btn btn-danger'%></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/pages/home.html.erb
<div class="jumbotron center">
  <h2 class="display-4">Welcome to RR Blogs </h2>
  <h3><p class="lead">Share your Thoughts and Explore More! </p></h3>
  <hr class="my-4">
  <%= link_to "Sign Up", signup_path, class:"btn btn-danger btn-lg btn-xlarge" %>
    <br/><br/>
    <br/><br/>
    <br/><br/>
    </div>

  <div class="container">
    <!-- Example row of columns -->
    <div class="row">
      <div class="col-md-4">
        <h2>Heading</h2>
        <p>Will you do the same for me? It's time to face the music I'm no longer your muse. Heard it's beautiful, be the judge and my girls gonna take a vote. I can feel a phoenix inside of me. Heaven is jealous of our love, angels are crying from up above. Yeah, you take me to utopia.</p>
        <p><a class="btn btn-primary btn-xlarge" href="#" role="button">View details &raquo;</a></p>
      </div>
      <div class="col-md-4">
        <h2>Heading</h2>
        <p>Standing on the frontline when the bombs start to fall. Heaven is jealous of our love, angels are crying from up above. Can't replace you with a million rings. Boy, when you're with me I'll give you a taste. There’s no going back. Before you met me I was alright but things were kinda heavy. Heavy is the head that wears the crown.</p>
        <p><a class="btn btn-primary btn-xlarge" href="#" role="button">View details &raquo;</a></p>
      </div>
      <div class="col-md-4">
        <h2>Heading</h2>
        <p>Playing ping pong all night long, everything's all neon and hazy. Yeah, she's so in demand. She's sweet as pie but if you break her heart. But down to earth. It's time to face the music I'm no longer your muse. I guess that I forgot I had a choice.</p>
        <p><a class="btn btn-primary btn-xlarge" href="#" role="button">View details &raquo;</a></p>
      </div>
    </div>
    <hr>
  </div> <!-- /container -->
  </main>


</div>

app/views/recipes/_form.html.erb
<div class="row">
  <div class="col-md-12">
  <%= form_with model: @recipe, :html => { class:"form-horizontal" , role:"form"} do |form| %>
      <div class="form-group">
          <div class="control-label col-md-2">
            <%= form.label :name %>
          </div>
          <div class="col-md-8">
            <%= form.text_field :name, class:"form-control",placeholder:'Blog Name', autofocus: true %>
          </div>
        </div>
        <div class="form-group">
          <div class="control-label col-md-2">
            <%= form.label :description %><br/>
          </div>
          <div class="col-md-8">
            <%= form.text_area :description, class:"form-control",placeholder:'Train of Thought',  size: "60x10" %>
          </div>
          </div>
        <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
          <%= form.submit "Create Thought",class:"btn btn-primary btn-lg btn-xlarge"%>
          </div>
        </div>
  <% end %>
<div class="col-md-offset-4">
  <%= link_to "Cancel and Back to All Thoughts", recipes_path,class:"btn btn-danger btn-small" %>
</div>
 </div>

app/views/recipes/_listings.html.erb
<% obj.each do |recipe|%>
  <div class="row">
    <div class="col-md-2">
      <section class="chef_info center">
        <%= link_to gravatar_for(recipe.chef, size: 120), chef_path(recipe.chef) %>
        <br/>
        <p><small> <%=recipe.chef.chefname%> </small></p>
      </section>
    </div>
    <br/>
  <div class="col-md-8 well">
    <h3 align="center"><%= link_to recipe.name,recipe_path(recipe)%> </h3>
    <p><%= truncate(recipe.description, length: 150)%> </p>
    <p><small>Created <%= time_ago_in_words(recipe.created_at) %> ago</small> </p>
          <%if logged_in? && ( current_user == recipe.chef || current_user.admin? ) %>
          <div class="recipe-actions">
              <%= link_to   "Edit Thought" ,edit_recipe_path(recipe), class:"btn btn-warning buttons"%>
              <%= button_to  "Destroy", recipe_path(recipe), data: { confirm: 'Are you sure?'}, method: :delete, class: "btn btn-danger buttons" %>
          </div>
        <%end%>
  </div>
</div>
<% end %>

app/views/recipes/edit.html.erb
<%= render "shared/pagetitle", pageTitle: "Edit : #{@recipe.name} " %>
<%= render "shared/errors", orm: @recipe %>
<%= render "form", orm: @recipe %>

app/views/recipes/index.html.erb
<div class="container">
<%= render 'shared/pagetitle', pageTitle:'All Thoughts'%>
<div align="center">
<%= will_paginate %>
</div>
<%= render 'listings', obj: @recipes  %>
</div>
<div align="center">
<%= will_paginate %>
</div>

app/views/recipes/new.html.erb
<%= render "shared/pagetitle", pageTitle: "Upload a new thought" %>
<%= render "shared/errors", orm: @recipe %>
<%= render "form" %>

app/views/recipes/show.html.erb
<div class="well container">
  <%= render 'shared/pagetitle', pageTitle: @recipe.name.capitalize %></h1>
  <div class="well row">
    <div class="col-md-10 col-md-offset-2">
     <h3 class="center description"><strong> Steps </strong></h3>
      <hr/>
      <p> <%= simple_format(@recipe.description) %> </p>
    </div>
  </div>
  <div class="row buttons">
    <div class="recipe-actions col-md-10-offset-1">
      <p class="center">
        <%= link_to gravatar_for(@recipe.chef, size: 120) ,chef_path(@recipe.chef)%><br/>
        <small align="center"> <%= @recipe.chef.chefname%> <br/>Created : <%= time_ago_in_words(@recipe.created_at)  %> Ago </small><br/>
        <% if logged_in? && ( current_user == @recipe.chef || current_user.admin? ) %>
          <div class="row recipe-actions buttons">
              <%= link_to   "Edit Thought" ,edit_recipe_path(@recipe), class:"btn btn-warning buttons"%>
              <%= link_to   "Destroy", recipe_path(@recipe), data: { confirm: 'Are you sure?'}, method: :delete, class: "btn btn-danger buttons" %>
          </div>
        <% end %>
      </p>
    </div>
   </div>
</div>

app/views/shared/_errors.html.erb
<% if orm.errors.any? %>
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <div class="panel panel-danger">
      <div class="panel-heading">
      <h2 class="panel-title"> <%= pluralize(orm.errors.count ,"errors") %> from saving this <%= orm.class%> </h2>
      </div>
      <div class="panel-body">
          <ul>
            <% orm.errors.full_messages.each do |msg|%>
            <li><%= msg%></li>
            <% end %>
          </ul>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/shared/_pagetitle.html.erb
<h1 align = "center"><%= pageTitle %></h1>
<hr/>